name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run lint:fix
      - run: echo ${{ <github> }}
      - run: echo ${{ <github.actor> }}
      - run: echo ${{ <env> }}
      - run: echo ${{ <job> }}
      - name: Commit files
        run: |
          git config --local user.email "felipe.delatorre@fivetalent.com"
          git config --local user.name "FelipeD-FiveTalent"
          git commit -am "Automated report"
          git push
        env:
          CI: true
